/*
 * Copyright (C) 2024 The Phosh Developers
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Author: Guido Günther <agx@sigxcpu.org>
 */

#define G_LOG_DOMAIN "phosh-style-manager"

#include "phosh-config.h"

#include "style-manager.h"
#include "util.h"

#include <gtk/gtk.h>
#include <gdesktop-enums.h>

#define IF_KEY_ACCENT_COLOR     "accent-color"
#define IF_KEY_COLOR_SCHEME     "color-scheme"
#define IF_SCHEMA_NAME          "org.gnome.desktop.interface"

/* Schema and key names live in util.h; the surfaces that request blur use
 * the same schema. */

/* A tint reads far stronger against a pale background, so the light variant
 * takes a proportion of the configured wash rather than all of it. Keeps the
 * default .2 landing on the .12 the light stylesheet was written around. */
#define GLASS_LIGHT_WASH_SCALE  0.6
/*
 * A light shadow needs less of itself than a dark one to read the same.
 * Measured on the lock screen clock: with identical geometry in both schemes,
 * the shadow's footprint is the same to within a pixel -- reach beyond the
 * glyph +3 up, +13 down, +11 right in dark against +3, +14, +11 in light --
 * but its visible mass sits +4 down and -3 left of the glyph in the dark
 * scheme and +12 down, +17 right in the light one. White against a mid tone
 * wallpaper simply carries further than black does, so the same alpha lands as
 * a heavier, more displaced shadow. Scaling it back is what makes the two
 * schemes look like the same shadow, which is the thing being asked for; the
 * offsets stay identical.
 */
#define GLASS_LIGHT_SHADOW_SCALE 0.65

/* Relative weights of the glass surfaces, against glass-opacity. These are the
 * alphas the stylesheets were designed with, expressed as ratios of .45, so
 * the default settings reproduce the hand-tuned look exactly. */
#define GLASS_RATIO_SHEET       1.0     /* top panel / drawer sheet, .45 */
#define GLASS_RATIO_TINT        0.556   /* settings menu layers,     .25 */
#define GLASS_RATIO_LOCK        1.111   /* lock screen sheet,        .50 */
#define GLASS_RATIO_FIELD       1.333   /* search bar,               .60 */
#define GLASS_RATIO_BUTTON      0.889   /* app grid buttons,         .40 */

/* Accent colors from gnome-shell src/st/st-theme-context.c */
#define ACCENT_COLOR_BLUE       "#3584e4"
#define ACCENT_COLOR_TEAL       "#2190a4"
#define ACCENT_COLOR_GREEN      "#3a944a"
#define ACCENT_COLOR_YELLOW     "#c88800"
#define ACCENT_COLOR_ORANGE     "#ed5b00"
#define ACCENT_COLOR_RED        "#e62d42"
#define ACCENT_COLOR_PINK       "#d56199"
#define ACCENT_COLOR_PURPLE     "#9141ac"
#define ACCENT_COLOR_SLATE      "#6f8396"
#define ACCENT_COLOR_FOREGROUND "#ffffff"

/**
 * PhoshStyleManager:
 *
 * The style manager is responsible for picking style sheets and
 * themes and notifying other parts of the shell about changes.
 */

enum {
  PROP_0,
  PROP_THEME_NAME,
  PROP_LAST_PROP
};
static GParamSpec *props[PROP_LAST_PROP];


struct _PhoshStyleManager {
  GObject         parent;

  char           *theme_name;
  GtkCssProvider *css_provider;
  GtkCssProvider *accent_css_provider;

  GSettings      *interface_settings;
  GSettings      *glass_settings;
};
G_DEFINE_TYPE (PhoshStyleManager, phosh_style_manager, G_TYPE_OBJECT)


/* First line of the file we generate. Anything without it is the user's own
 * and is left alone. */
#define APP_CSS_MARKER "/* Generated by phosh from io.furios.phosh.shell -- edits are overwritten. */"

/* Least glass an application window keeps, whatever glass-opacity says */
#define APP_MIN_OPACITY 0.12


static void
mix_rgba (GdkRGBA *out, const GdkRGBA *a, const GdkRGBA *b, double f)
{
  out->red   = a->red   + (b->red   - a->red)   * f;
  out->green = a->green + (b->green - a->green) * f;
  out->blue  = a->blue  + (b->blue  - a->blue)  * f;
  out->alpha = 1.0;
}


static char *
rgba_css (const GdkRGBA *c, double alpha)
{
  return g_strdup_printf ("rgba(%d,%d,%d,%.3f)",
                          (int) (CLAMP (c->red,   0.0, 1.0) * 255.0 + 0.5),
                          (int) (CLAMP (c->green, 0.0, 1.0) * 255.0 + 0.5),
                          (int) (CLAMP (c->blue,  0.0, 1.0) * 255.0 + 0.5),
                          CLAMP (alpha, 0.0, 1.0));
}


/* The glass colour the shell's CSS arrives at, computed here in numbers so the
 * text colour and the app stylesheet can both reason about it. Mirrors the
 * mix() chain generated for @phosh_glass_bg_color. */
static void
compute_glass (GdkRGBA    *out,
               const char *accent,
               gboolean    prefer_dark,
               double      lightness,
               double      wash)
{
  GdkRGBA base, white = { 1.0, 1.0, 1.0, 1.0 }, acc;

  gdk_rgba_parse (&base, prefer_dark ? "#16161a" : "#ececf2");
  if (!gdk_rgba_parse (&acc, accent))
    acc = base;

  mix_rgba (out, &base, &white, lightness);
  mix_rgba (out, out, &acc, wash);
}


/**
 * update_app_stylesheet:
 *
 * Write ~/.config/gtk-4.0/gtk.css so GTK4 applications carry the same glass as
 * the shell: same accent, same tint, same translucency, same text colour.
 *
 * Unlike the shell's own stylesheet this cannot be applied live -- GTK4 reads
 * the user stylesheet once at startup and does not watch it -- so apps pick
 * changes up the next time they are launched.
 *
 * The palette has to be repeated here in numbers, because the shell's copy
 * lives in CSS where the app has no way to reach it.
 */
static void
update_app_stylesheet (PhoshStyleManager *self,
                       const char        *accent,
                       const GdkRGBA     *glass,
                       const char        *fg_hex,
                       const char        *accent_fg_hex,
                       double             opacity,
                       double             text_opacity)
{
  g_autofree char *path = NULL;
  g_autofree char *dir = NULL;
  g_autofree char *existing = NULL;
  g_autofree char *css = NULL;
  g_autofree char *c_window = NULL, *c_header = NULL, *c_view = NULL;
  g_autofree char *c_popover = NULL, *c_dialog = NULL, *c_card = NULL;
  g_autofree char *c_text = NULL, *c_accent = NULL;
  g_autoptr (GError) err = NULL;
  GdkRGBA accent_rgba, fg;

  dir = g_build_filename (g_get_user_config_dir (), "gtk-4.0", NULL);
  path = g_build_filename (dir, "gtk.css", NULL);

  /* Never clobber a stylesheet we did not write */
  if (g_file_get_contents (path, &existing, NULL, NULL) &&
      !g_str_has_prefix (existing, APP_CSS_MARKER)) {
    g_debug ("%s was not generated by us, leaving it alone", path);
    return;
  }

  if (!gdk_rgba_parse (&accent_rgba, accent))
    return;

  if (!gdk_rgba_parse (&fg, fg_hex))
    gdk_rgba_parse (&fg, "#ffffff");

  /* Applications keep a floor of glass. At zero every surface below is fully
   * transparent, which makes the other settings look broken -- lightness and
   * wash still compute, but they paint a colour with no alpha -- and leaves
   * app text floating unreadably on the wallpaper. The shell is left exact,
   * where a fully transparent panel over the blur is a legitimate look. */
  opacity = MAX (opacity, APP_MIN_OPACITY);

  c_window  = rgba_css (glass, opacity * 1.222);          /* .55 at the default .45 */
  c_header  = rgba_css (glass, opacity * 0.889);          /* .40 */
  c_view    = rgba_css (glass, opacity * 0.778);          /* .35 */
  c_card    = rgba_css (&accent_rgba, opacity * 0.267);    /* .12 */
  /* Transient surfaces stay readable whatever the glass is set to */
  c_popover = rgba_css (glass, MAX (opacity * 1.5, 0.9));
  c_dialog  = rgba_css (glass, MAX (opacity * 1.5, 0.9));
  c_text    = rgba_css (&fg, text_opacity);
  c_accent  = rgba_css (&accent_rgba, 1.0);

  css = g_strdup_printf (
    APP_CSS_MARKER "\n"
    "/* Delete this file to opt out; phosh will not recreate it while it\n"
    "   contains anything else. GTK4 reads this once at startup, so changes\n"
    "   appear the next time an application is launched. */\n"
    "\n"
    "@define-color window_bg_color %s;\n"
    "@define-color headerbar_bg_color %s;\n"
    "@define-color headerbar_backdrop_color %s;\n"
    "@define-color sidebar_bg_color %s;\n"
    "@define-color sidebar_backdrop_color %s;\n"
    "@define-color secondary_sidebar_bg_color %s;\n"
    "@define-color view_bg_color %s;\n"
    "@define-color card_bg_color %s;\n"
    "@define-color popover_bg_color %s;\n"
    "@define-color dialog_bg_color %s;\n"
    /* Every foreground libadwaita knows about. Setting only window_fg_color
       left the rows inside a boxed list white, since those take
       card_fg_color, while the group headings above them changed. The two
       theme_* names are GTK's own, for widgets that predate libadwaita. */
    "@define-color window_fg_color %s;\n"
    "@define-color view_fg_color %s;\n"
    "@define-color headerbar_fg_color %s;\n"
    "@define-color card_fg_color %s;\n"
    "@define-color dialog_fg_color %s;\n"
    "@define-color popover_fg_color %s;\n"
    "@define-color sidebar_fg_color %s;\n"
    "@define-color secondary_sidebar_fg_color %s;\n"
    "@define-color thumbnail_fg_color %s;\n"
    "@define-color thumbnail_bg_color %s;\n"
    "@define-color theme_fg_color %s;\n"
    "@define-color theme_text_color %s;\n"
    "@define-color accent_bg_color %s;\n"
    "@define-color accent_color %s;\n"
    "@define-color accent_fg_color %s;\n",
    c_window, c_header, c_window, c_header, c_window, c_header,
    c_view, c_card, c_popover, c_dialog,
    c_text, c_text, c_text, c_text, c_text, c_text, c_text, c_text, c_text,
    c_view, c_text, c_text,
    c_accent, c_accent, accent_fg_hex);

  if (g_mkdir_with_parents (dir, 0755) != 0) {
    g_warning ("Could not create %s", dir);
    return;
  }

  if (!g_file_set_contents (path, css, -1, &err))
    g_warning ("Could not write %s: %s", path, err->message);
  else
    g_debug ("Wrote app stylesheet %s", path);
}


static void
on_accent_color_changed (PhoshStyleManager *self)
{
  const char *color;
  g_autofree char *css  = NULL;
  g_autoptr (GtkCssProvider) provider = gtk_css_provider_new ();
  g_autofree char *custom = NULL;
  g_autofree char *custom_hex = NULL;
  g_autofree char *text_custom = NULL;
  g_autofree char *text_hex = NULL;
  const char *fg_hex, *fg_css, *accent_fg, *accent_fg_css;
  g_autofree char *accent_text_custom = NULL;
  g_autofree char *accent_text_hex = NULL;
  g_autofree char *shadow_custom = NULL;
  g_autofree char *shadow_hex = NULL;
  const char *shadow_css;
  GdkRGBA glass;
  double opacity, lightness, wash, text_opacity, text_shadow;
  gboolean prefer_dark;

  if (self->accent_css_provider) {
    gtk_style_context_remove_provider_for_screen (gdk_screen_get_default (),
                                                  GTK_STYLE_PROVIDER (self->accent_css_provider));
  }

  /* Only enable accent colors on Adwaita */
  if ((g_strcmp0 (self->theme_name, "Adwaita") != 0) && (g_strcmp0 (self->theme_name, "Adwaita-dark") != 0) && (g_strcmp0 (self->theme_name, "adw-gtk3") != 0) && (g_strcmp0 (self->theme_name, "adw-gtk3-dark") != 0))
    return;

  switch (g_settings_get_enum (self->interface_settings, IF_KEY_ACCENT_COLOR)) {
  case G_DESKTOP_ACCENT_COLOR_TEAL:
    color = ACCENT_COLOR_TEAL;
    break;
  case G_DESKTOP_ACCENT_COLOR_GREEN:
    color = ACCENT_COLOR_GREEN;
    break;
  case G_DESKTOP_ACCENT_COLOR_YELLOW:
    color = ACCENT_COLOR_YELLOW;
    break;
  case G_DESKTOP_ACCENT_COLOR_ORANGE:
    color = ACCENT_COLOR_ORANGE;
    break;
  case G_DESKTOP_ACCENT_COLOR_RED:
    color = ACCENT_COLOR_RED;
    break;
  case G_DESKTOP_ACCENT_COLOR_PINK:
    color = ACCENT_COLOR_PINK;
    break;
  case G_DESKTOP_ACCENT_COLOR_PURPLE:
    color = ACCENT_COLOR_PURPLE;
    break;
  case G_DESKTOP_ACCENT_COLOR_SLATE:
    color = ACCENT_COLOR_SLATE;
    break;
  case G_DESKTOP_ACCENT_COLOR_BLUE:
  default:
    color = ACCENT_COLOR_BLUE;
  }

  /* A custom colour, if set, wins over the nine presets. Re-serialise it
   * rather than pasting the setting straight into the stylesheet: this string
   * is interpolated into CSS, so only a colour may come out of it. */
  custom = g_settings_get_string (self->glass_settings, PHOSH_GLASS_KEY_ACCENT_CUSTOM);
  if (custom && *custom) {
    GdkRGBA rgba;

    if (gdk_rgba_parse (&rgba, custom)) {
      custom_hex = g_strdup_printf ("#%02x%02x%02x",
                                    (int) (CLAMP (rgba.red,   0.0, 1.0) * 255.0 + 0.5),
                                    (int) (CLAMP (rgba.green, 0.0, 1.0) * 255.0 + 0.5),
                                    (int) (CLAMP (rgba.blue,  0.0, 1.0) * 255.0 + 0.5));
      color = custom_hex;
    } else {
      g_warning ("Ignoring unparseable custom accent color '%s'", custom);
    }
  }

  /* Text colour, same treatment as the accent: parsed and re-serialised
   * rather than pasted into the stylesheet. Empty follows the theme, which is
   * what @phosh_fg_base_color holds. */
  text_custom = g_settings_get_string (self->glass_settings, PHOSH_GLASS_KEY_TEXT_COLOR);
  if (text_custom && *text_custom) {
    GdkRGBA rgba;

    if (gdk_rgba_parse (&rgba, text_custom)) {
      text_hex = g_strdup_printf ("#%02x%02x%02x",
                                  (int) (CLAMP (rgba.red,   0.0, 1.0) * 255.0 + 0.5),
                                  (int) (CLAMP (rgba.green, 0.0, 1.0) * 255.0 + 0.5),
                                  (int) (CLAMP (rgba.blue,  0.0, 1.0) * 255.0 + 0.5));
    } else {
      g_warning ("Ignoring unparseable text color '%s'", text_custom);
    }
  }

  text_opacity = g_settings_get_double (self->glass_settings, PHOSH_GLASS_KEY_TEXT_OPACITY);
  opacity   = g_settings_get_double (self->glass_settings, PHOSH_GLASS_KEY_OPACITY);
  lightness = g_settings_get_double (self->glass_settings, PHOSH_GLASS_KEY_LIGHTNESS);
  wash      = g_settings_get_double (self->glass_settings, PHOSH_GLASS_KEY_ACCENT_WASH);

  prefer_dark = g_settings_get_enum (self->interface_settings, IF_KEY_COLOR_SCHEME) ==
                G_DESKTOP_COLOR_SCHEME_PREFER_DARK;
  if (!prefer_dark)
    wash *= GLASS_LIGHT_WASH_SCALE;


  /* Resolve the text colour before generating anything: an explicit choice
   * wins, otherwise follow the glass, so that pushing the wash and lightness
   * to a bright accent flips the text dark instead of leaving white on
   * near-white. */
  compute_glass (&glass, color, prefer_dark, lightness, wash);

  /* Every piece of text in the shell follows glass-text-color, including the
   * text on an accent fill. Deriving that one from the accent's luminance was
   * defensible on contrast grounds and confusing in practice: the rule is
   * invisible, it cannot be watched changing while a slider moves, and it
   * makes the setting look ignored. Empty falls back to the theme's own
   * foreground, and glass-accent-text-color overrides just the accent case. */
  fg_css = text_hex ? text_hex : "@phosh_fg_base_color";
  fg_hex = text_hex ? text_hex : (prefer_dark ? "#ffffff" : "#000000");

  /* Text sitting *on* the accent is a different question from text on the
   * glass: a selected quick setting, a pressed key, a card. White was
   * hardcoded, which is wrong for a light accent -- yellow especially. */
  accent_text_custom = g_settings_get_string (self->glass_settings, PHOSH_GLASS_KEY_ACCENT_TEXT);
  if (accent_text_custom && *accent_text_custom) {
    GdkRGBA rgba;

    if (gdk_rgba_parse (&rgba, accent_text_custom))
      accent_text_hex = g_strdup_printf ("#%02x%02x%02x",
                                         (int) (CLAMP (rgba.red,   0.0, 1.0) * 255.0 + 0.5),
                                         (int) (CLAMP (rgba.green, 0.0, 1.0) * 255.0 + 0.5),
                                         (int) (CLAMP (rgba.blue,  0.0, 1.0) * 255.0 + 0.5));
    else
      g_warning ("Ignoring unparseable accent text color '%s'", accent_text_custom);
  }

  accent_fg_css = accent_text_hex ? accent_text_hex : fg_css;
  accent_fg = accent_text_hex ? accent_text_hex : fg_hex;

  /* The drop shadow behind the shell's text. It matters most on the lock
   * screen, whose labels sit over a wallpaper the shell did not choose and
   * cannot predict. Empty follows the colour scheme: black in dark mode, white
   * in light mode.
   *
   * Deriving it from the text colour instead was the first attempt and it is
   * wrong in the case that matters. glass-text-color is a single value shared
   * by both schemes, so pinning the text to white -- an ordinary thing to do --
   * left light mode computing a black shadow and the rule looking broken. The
   * scheme is the thing the user is actually switching. */
  shadow_custom = g_settings_get_string (self->glass_settings, PHOSH_GLASS_KEY_SHADOW_COLOR);
  if (shadow_custom && *shadow_custom) {
    GdkRGBA rgba;

    if (gdk_rgba_parse (&rgba, shadow_custom))
      shadow_hex = g_strdup_printf ("#%02x%02x%02x",
                                    (int) (CLAMP (rgba.red,   0.0, 1.0) * 255.0 + 0.5),
                                    (int) (CLAMP (rgba.green, 0.0, 1.0) * 255.0 + 0.5),
                                    (int) (CLAMP (rgba.blue,  0.0, 1.0) * 255.0 + 0.5));
    else
      g_warning ("Ignoring unparseable text shadow color '%s'", shadow_custom);
  }

  /* Opposite the text that is actually in use -- not opposite the colour
   * scheme. With nothing set those are the same thing, because the scheme
   * picks white text or black text; the difference appears the moment
   * glass-text-color is set, and that is exactly when it matters.
   *
   * The case: a black wallpaper under the light scheme. The default black text
   * disappears into it and only the white shadow is visible, which reads as a
   * halo around nothing. The intended escape is to set the text white -- but
   * with the shadow keyed off the scheme it stayed white too, white on white,
   * so the fix needed a second setting to work and looked broken until both
   * were found. Keyed off the text, setting the text alone is enough.
   *
   * Deriving it from the text was tried once before and reverted, on the
   * grounds that pinning the text to white made the light scheme compute a
   * black shadow. That is the correct answer and was misread as a bug: white
   * text needs a dark shadow whatever scheme it is in.
   *
   * Note what this is NOT responsible for, because it absorbed the blame for
   * it twice: the wide dark halo around the panel and the cards in the light
   * scheme was the hardcoded rgba(0,0,0,.2-.35) box-shadows in common.css,
   * which the light variant never overrode. Those are overridden now, in
   * adwaita-light.css. */
  if (shadow_hex) {
    shadow_css = shadow_hex;
  } else {
    GdkRGBA fg_rgba;
    double luminance = prefer_dark ? 1.0 : 0.0;

    if (gdk_rgba_parse (&fg_rgba, fg_hex))
      luminance = 0.2126 * fg_rgba.red + 0.7152 * fg_rgba.green + 0.0722 * fg_rgba.blue;

    shadow_css = luminance > 0.5 ? "#000000" : "#ffffff";
  }

  text_shadow = CLAMP (g_settings_get_double (self->glass_settings,
                                              PHOSH_GLASS_KEY_TEXT_SHADOW), 0.0, 1.0);
  if (!prefer_dark)
    text_shadow *= GLASS_LIGHT_SHADOW_SCALE;

  g_debug ("Setting accent bg color to %s; glass opacity %.2f, lightness %.2f, wash %.2f, "
           "text %s", color, opacity, lightness, wash, fg_hex);

  /* The glass colours are built out of @phosh_bg_color, which the loaded
   * stylesheet defines, so this stays correct for both the light and the dark
   * variant without repeating either palette here. Each variant also defines
   * all of these itself, which is what a non-Adwaita theme falls back on --
   * this function returns early for those. */
  css = g_strdup_printf ("@define-color theme_selected_bg_color %s;\n"
                         "@define-color theme_selected_fg_color alpha(%s, %.3f);\n"
                         "@define-color phosh_glass_bg_color "
                         "mix(mix(@phosh_bg_color, #ffffff, %.3f), %s, %.3f);\n"
                         "@define-color phosh_glass_sheet_color alpha(@phosh_glass_bg_color, %.3f);\n"
                         "@define-color phosh_glass_tint_color alpha(@phosh_glass_bg_color, %.3f);\n"
                         "@define-color phosh_glass_lock_color alpha(@phosh_glass_bg_color, %.3f);\n"
                         "@define-color phosh_glass_field_color alpha(@phosh_glass_bg_color, %.3f);\n"
                         "@define-color phosh_glass_button_color alpha(@phosh_glass_bg_color, %.3f);\n"
                         "@define-color phosh_text_shadow_color alpha(%s, %.3f);\n"
                         "@define-color phosh_fg_color alpha(%s, %.3f);",
                         color, accent_fg_css, CLAMP (text_opacity, 0.2, 1.0),
                         lightness, color, wash,
                         CLAMP (opacity * GLASS_RATIO_SHEET,  0.0, 1.0),
                         CLAMP (opacity * GLASS_RATIO_TINT,   0.0, 1.0),
                         CLAMP (opacity * GLASS_RATIO_LOCK,   0.0, 1.0),
                         CLAMP (opacity * GLASS_RATIO_FIELD,  0.0, 1.0),
                         CLAMP (opacity * GLASS_RATIO_BUTTON, 0.0, 1.0),
                         shadow_css, text_shadow,
                         fg_css,
                         CLAMP (text_opacity, 0.2, 1.0));
  gtk_css_provider_load_from_data (provider, css, -1, NULL);
  gtk_style_context_add_provider_for_screen (gdk_screen_get_default (),
                                             GTK_STYLE_PROVIDER (provider),
                                             GTK_STYLE_PROVIDER_PRIORITY_APPLICATION + 1);
  g_set_object (&self->accent_css_provider, provider);

  /* Keep applications in step with the shell. They only pick this up when
   * they next start, which is the best GTK4 allows. */
  update_app_stylesheet (self, color, &glass, fg_hex, accent_fg, opacity,
                         CLAMP (text_opacity, 0.2, 1.0));
}


static void
update_stylesheet (PhoshStyleManager *self)
{
  const char *style;
  gboolean prefer_dark;
  g_autoptr (GtkCssProvider) provider = gtk_css_provider_new ();

  prefer_dark = g_settings_get_enum (self->interface_settings, IF_KEY_COLOR_SCHEME) ==
                G_DESKTOP_COLOR_SCHEME_PREFER_DARK;

  g_object_set (gtk_settings_get_default (),
                "gtk-application-prefer-dark-theme", prefer_dark, NULL);

  if (self->css_provider) {
    gtk_style_context_remove_provider_for_screen (gdk_screen_get_default (),
                                                  GTK_STYLE_PROVIDER (self->css_provider));
  }

  if (g_strcmp0 (self->theme_name, "HighContrast") == 0)
    style = "/mobi/phosh/stylesheet/adwaita-hc-light.css";
  else if (!prefer_dark)
    style = "/mobi/phosh/stylesheet/adwaita-light.css";
  else
    style = phosh_style_manager_get_stylesheet (self->theme_name);

  g_debug ("Loading stylesheet %s", style);

  gtk_css_provider_load_from_resource (provider, style);
  gtk_style_context_add_provider_for_screen (gdk_screen_get_default (),
                                             GTK_STYLE_PROVIDER (provider),
                                             GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
  g_set_object (&self->css_provider, provider);

  /* Refresh accent color */
  on_accent_color_changed (self);
}


static void
on_color_scheme_changed (PhoshStyleManager *self)
{
  update_stylesheet (self);
}


static void
on_gtk_theme_name_changed (PhoshStyleManager *self, GParamSpec *pspec, GtkSettings *settings)
{
  g_autofree char *name = NULL;

  g_object_get (settings, "gtk-theme-name", &name, NULL);

  if (g_strcmp0 (self->theme_name, name) == 0)
    return;

  self->theme_name = g_steal_pointer (&name);
  g_debug ("GTK theme: %s", self->theme_name);

  update_stylesheet (self);

  g_object_notify_by_pspec (G_OBJECT (self), props[PROP_THEME_NAME]);
}


static void
phosh_style_manager_get_property (GObject    *object,
                                  guint       property_id,
                                  GValue     *value,
                                  GParamSpec *pspec)
{
  PhoshStyleManager *self = PHOSH_STYLE_MANAGER (object);

  switch (property_id) {
  case PROP_THEME_NAME:
    g_value_set_string (value, self->theme_name);
    break;
  default:
    G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
    break;
  }
}


static void
phosh_style_manager_dispose (GObject *object)
{
  PhoshStyleManager *self = PHOSH_STYLE_MANAGER (object);

  g_clear_pointer (&self->theme_name, g_free);
  g_clear_object (&self->css_provider);
  g_clear_object (&self->accent_css_provider);

  g_clear_object (&self->interface_settings);
  g_clear_object (&self->glass_settings);

  G_OBJECT_CLASS (phosh_style_manager_parent_class)->dispose (object);
}


static void
phosh_style_manager_class_init (PhoshStyleManagerClass *klass)
{
  GObjectClass *object_class = G_OBJECT_CLASS (klass);

  object_class->get_property = phosh_style_manager_get_property;
  object_class->dispose = phosh_style_manager_dispose;

  props[PROP_THEME_NAME] =
    g_param_spec_string ("theme-name", "", "",
                         NULL,
                         G_PARAM_READABLE | G_PARAM_STATIC_STRINGS | G_PARAM_EXPLICIT_NOTIFY);

  g_object_class_install_properties (object_class, PROP_LAST_PROP, props);
}


static void
phosh_style_manager_init (PhoshStyleManager *self)
{
  GtkSettings *gtk_settings = gtk_settings_get_default ();

  self->interface_settings = g_settings_new (IF_SCHEMA_NAME);
  self->glass_settings = g_settings_new (PHOSH_GLASS_SCHEMA_ID);

  g_signal_connect_swapped (self->interface_settings,
                            "changed::" IF_KEY_ACCENT_COLOR,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  /* The glass colours are regenerated by the same path as the accent */
  g_signal_connect_swapped (self->glass_settings,
                            "changed::" PHOSH_GLASS_KEY_ACCENT_CUSTOM,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  g_signal_connect_swapped (self->glass_settings,
                            "changed::" PHOSH_GLASS_KEY_OPACITY,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  g_signal_connect_swapped (self->glass_settings,
                            "changed::" PHOSH_GLASS_KEY_LIGHTNESS,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  g_signal_connect_swapped (self->glass_settings,
                            "changed::" PHOSH_GLASS_KEY_ACCENT_WASH,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  g_signal_connect_swapped (self->glass_settings,
                            "changed::" PHOSH_GLASS_KEY_TEXT_COLOR,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  g_signal_connect_swapped (self->glass_settings,
                            "changed::" PHOSH_GLASS_KEY_ACCENT_TEXT,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  g_signal_connect_swapped (self->glass_settings,
                            "changed::" PHOSH_GLASS_KEY_TEXT_OPACITY,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  /* Both shadow keys were missing from this list, so neither the strength
   * slider nor the colour did anything until some *other* key or the colour
   * scheme happened to regenerate the provider. That is why the shadow looked
   * like it only responded sometimes. */
  g_signal_connect_swapped (self->glass_settings,
                            "changed::" PHOSH_GLASS_KEY_TEXT_SHADOW,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  g_signal_connect_swapped (self->glass_settings,
                            "changed::" PHOSH_GLASS_KEY_SHADOW_COLOR,
                            G_CALLBACK (on_accent_color_changed),
                            self);
  g_signal_connect_swapped (self->interface_settings,
                            "changed::" IF_KEY_COLOR_SCHEME,
                            G_CALLBACK (on_color_scheme_changed),
                            self);
  g_signal_connect_swapped (gtk_settings,
                            "notify::gtk-theme-name",
                            G_CALLBACK (on_gtk_theme_name_changed),
                            self);
  on_gtk_theme_name_changed (self, NULL, gtk_settings);
}


PhoshStyleManager *
phosh_style_manager_new (void)
{
  return g_object_new (PHOSH_TYPE_STYLE_MANAGER, NULL);
}

/**
 * phosh_style_manager_get_stylesheet:
 * @theme_name: A theme name
 *
 * Get the proper style sheet based on the given theme name
 */
const char *
phosh_style_manager_get_stylesheet (const char *theme_name)
{
  const char *style;

  if (g_strcmp0 (theme_name, "HighContrast") == 0)
    style = "/mobi/phosh/stylesheet/adwaita-hc-light.css";
  else
    style = "/mobi/phosh/stylesheet/adwaita-dark.css";

  return style;
}

/**
 * phosh_style_manager_get_theme_name:
 * @self; The style manager
 *
 * Get the current theme name
 *
 * Returns: The theme name
 */
const char *
phosh_style_manager_get_theme_name (PhoshStyleManager *self)
{
  g_return_val_if_fail (PHOSH_IS_STYLE_MANAGER (self), NULL);

  return self->theme_name;
}

/**
 * phosh_style_manager_is_high_contrast:
 * @self; The style manager
 *
 * Get whether the current theme is a high contrast theme
 *
 * Returns: `True` if current theme is high contrast
 */
gboolean
phosh_style_manager_is_high_contrast (PhoshStyleManager *self)
{
  g_return_val_if_fail (PHOSH_IS_STYLE_MANAGER (self), FALSE);

  return g_strcmp0 (self->theme_name, "HighContrast") == 0;
}
